resource_group_name  = "rg-dev-storage"
location             = "Central India"
storage_account_name = "tanyastorage11111"
account_tier         = "Standard"
replication_type     = "LRS"
environment          = "dev"